
#+TITLE: RRF Development Board
#+LANGUAGE: en
#+EMAIL: tnesland at gmail dot com
#+OPTIONS: H:2 num:nil toc:2 \n:nil @"t ::t |:t *:t TeX:t author:nil <:t
#+STYLE: </style><link rel="stylesheet" href="./css/org.css" type="text/css" />

* Components

** TK-Session
   
   Acts as the controller object for the entire session.
   
   - [[./release/tk-session][Downloads]]
   - [[./projects/tk-session/index.html#Installation][Installation / Update Process]]
   - [[./projects/tk-session/index.html][Project Page]]

** TK-Utility

   Utility framework shared between session controller and individual
   component bundles.

   - [[./release/tk-utility][Downloads]] 
   - [[./projects/tk-utility/index.html#Installation][Installation / Update Process]]
   - [[./projects/tk-utility/index.html][Project Page]]

** Bundles
   - [[./release/bundles][Downloads]]
   - [[./projects/bundles/index.html#Installation][Installation / Update Process]]
   - [[./projects/bundles/index.html#sec-2_2][Step-By-Step Guide For Creating A Bundle]]
   - [[How do I know if my bundles are up to date?][Check If Bundles Are Up-To-Date]]
   - [[./projects/bundles/index.html][Project Page]]

** Blood Pressure Controller

   Controller for *DINAMAP PRO 200*

   - [[./release/bp][Downloads]]
   - [[./projects/bp/index.html][Project Page]]

* FAQ

** What is the procedure to install every component on a new machine?
   
   1) Install the shared utility framework. See [[./projects/tk-utility/index.html#Installation][notes]].
   2) Install the session controller. See [[./projects/tk-session/index.html#Installation][notes]].
   3) If bundles are out of date ([[How do I know if my bundles are up
      to date?][How do I know if my bundles are up to date?]]), download and install
      current bundle package. See [[./projects/bundles/index.html#Installation][notes]].

** The session is jumping to a component in the middle of the session instead of starting at the beginning. How do I prevent this?
   
   This is the expected recovery behavior for the session. Most
   likely a registry file still exists in the session's temporary
   directory and it is trying to recover because this is the defined
   recovery condition. If you want to reset, *note that you will lose
   any information from the crashed session*, you will need to find
   and remove:

   : /Applications/TK-Session.app/Contents/_TEMP/regfile.plist

   After this, restarting the program should result in a fresh start.
   
** The program is crashing, but I'm not sure why. Where can I find helpful information?
   
   The session controller logs important information to the
   Console. In the event of a crash, it is the session controller's
   intention to log useful information for further analysis. You can
   access this information by opening Console application found at:

   : /Applications/Utilities/Console.app

** How do I know if my bundles are up to date?
   
   This currently requires many steps . . . I'm debating whether I
   should write a helper function for this. You basically have to
   look into the Contents directory of each bundle and read the
   version number from the plist file.

    
* Raw Source Code

  Here is *everything*: [[./release/dev_directory.zip][all teh codez]]

